### ISSUE TITLE
Мерцание не исчезает если использовать Custom Styles (скины грубо говоря)

### ISSUE THREAD

**Issue by vectoris** [errorcalc/FreeEsVCLComponents#10]
Собственно вся суть в названии темы, без скинов всё работает, ставишь скин всё мерцает при ресайзе.

**Comment by errorcalc** [comment]
Пожалуйста, предоставте дополнительные подробности, в какой версии мерацает, какой компонент и т.д., в идеале лучше всего предоставить минимальный пример проекта воспроизводящего проблему.

**Comment by errorcalc** [comment]
do not reproduce
