### ISSUE TITLE
TEsImageControl

### ISSUE THREAD

**Issue by kazuser** [errorcalc/FreeEsVCLComponents#12]
А как вообще работает TEsImageControl?

Пытаюсь показать полупрозрачный круг:

![Frame 59](https://github.com/errorcalc/FreeEsVclComponents/assets/3335273/0ea9db3e-8970-4d3e-81b3-a79ba5248533)

Вроде всё выставлено как надо, но круг не прозрачный (я ожидал, что кнопку будет видно):
![image](https://github.com/errorcalc/FreeEsVclComponents/assets/3335273/3b5c5759-3cb5-466b-ab72-5b303bd3da01)

**Comment by errorcalc** [comment]
TEsImageControl - это наследник TWinControl, через него и не должны "просвечивать" другие TWinControl-ы, такие как TButton, но "просвечивают" TGraphicControl-ы, такие как TShape.
Адекватного способа получить "истинную" полупрозрачность оконных элементов управления в Windows - не существует, кроме стиля WS_EX_LAYERED, но и там свои нюансы: https://habr.com/ru/articles/247397/
TEsImageControl создан "оконным" для устранения мерцания, присущего стандартному TImage.

Какая у вас стоит задача?

**Comment by kazuser** [comment]
Нужно показать поверх всей формы со всеми её потрохами (кнопки, панели, веб-браузер, и т.д.) один полупрозрачный водяной знак (SVG или хотя бы PNG) — ищу способы, но их, похоже, в VCL нет :(

**Comment by errorcalc** [comment]
По ссылке выше вы можете прочитать как это сделать с помощью назначения окну контрола стиля WS_EX_LAYERED, но это будет работать только начиная с Windows 8. 
Если же нужна поддержка Windows 7 то придется отображать окно верхнего уровня над формой со стилем WS_EX_LAYERED, и синхронизировать положение этого окна.

**Comment by kazuser** [comment]
Это прям то, что нужно! 🔥

Большое спасибо за помощь! 👍
