### ISSUE TITLE
Проблема с установкой в Delphi XE8

### ISSUE THREAD

**Issue by 9223000** [errorcalc/FreeEsVCLComponents#3]
Не получается установить в Delphi XE8

Все делаю согласно инструкции:
0. Полностью удалите предыдущую версию!
1. Добавьте путь к папке "Source" в search path (Tools->Options->Delphi Options->Library->Library path)
2. Если вы планируете установить компоненты одновременно в нескольких версиях Delphi на компьютере, то запустите 
"Packages\PackagesGenerator.exe" и выберите соответствующие сгенерированные файлы проекта.
3. Откройте группу проектов "ErrorSoftGroup.groupproj" 
4. Сделайте билд(Build) "EsCore.bpl"
5. Сделайте билд(Build) "EsVclCore.bpl"
6. Сделайте билд(Build) "EsVclComponents.bpl"
7. Проинсталлируйте(Install) "EsVclComponentsDesign.bpl"

Но на шаге "Проинсталлируйте(Install) "EsVclComponentsDesign.bpl" возникает ошибка:
Access violation at address 68A687D1 in module "bds.exe". Read of address 00000010

При попытке установить "EsVclComponentsDesign.bpl" через Component \ Install Packages, возникает аналогичная ошибка.

**Comment by errorcalc** [comment]
Проблем с установкой не должно быть, 
1. Вы точно правильно прописали пути в Library path?
2. Вы впервые устанавливаете EsVclComponents?
3. Какая версия Windows?
4. У вас установлены AlphaSkins?

**Comment by 9223000** [comment]
> 1. Вы точно правильно прописали пути в Library path?
Да

> 2. Вы впервые устанавливаете EsVclComponents?
Да

> 3. Какая версия Windows?
Windows 10 Enterprise 1709

> 4. У вас установлены AlphaSkins?
Нет

**Comment by errorcalc** [comment]
Перепроверил, установка проходит успешно, попробуйте сделать CleanAll в Project Group, и установить снова.
