### ISSUE TITLE
Entry point error

### ISSUE THREAD

**Issue by interlan** [errorcalc/FreeEsVCLComponents#5]
While installing design time package (after building all) it fails with an error about some entry point in bpl. (Delphi Rio)
The same happens with EsGroupBar!

**Comment by errorcalc** [comment]
Did you install FreeEsVclComponents in previous versions of Delphi?
Or is this the first installation of FreeEsVclComponents?

**Comment by interlan** [comment]
As I can trace back, in Tokyo the version downloaded in February failed, but later versions from April 2018 installed fine.

**Comment by errorcalc** [comment]
If you need to install FreeEsVclComponents in several versions of Delphi, you can use https://github.com/errorcalc/FreeEsVclComponents/blob/master/Packages/ for generate individual packages for every versions.

**Comment by errorcalc** [comment]
@interlan 
Did you use advice?
Is you have a error now?

**Comment by interlan** [comment]
After downloading the files today 14-12-2018 and using your packages generator to produce installation files for Rio, it installed !!!
I started exploring the components.
Thank you!

**Comment by errorcalc** [comment]
@interlan Great!
