### ISSUE TITLE
EsActivityBar does not update while application is busy

### ISSUE THREAD

**Issue by PeterPanino** [errorcalc/FreeEsVCLComponents#8]
Tried the \ErrorSoftVCLComponents-4.1.0-11\Samples\ActivityBar example in Alexandria. Works well while application is idle but:

```
procedure TMainForm.ckbActiveClick(Sender: TObject);
begin
  EsActivityBar.Active := TCheckBox(Sender).Checked;

  // EsActivityBar does not update while looping:
  if EsActivityBar.Active then
  begin
     for var i := 1 to 100000 do
       Self.Caption := FormatDateTime('YYMMDDHHSSZZZ', Now);
  end;
end;
```

Needs threading. Can you implement threading?

**Comment by errorcalc** [comment]
When you do lengthy calculations on the main(UI) thread, you are essentially "locking" the user interface and all of its components.
Use threads or call Application.ProcessMessages; in a loop (but I don't recommend this approach)
