### ISSUE TITLE
Won't install Delphi 11

### ISSUE THREAD

**Issue by jaddwooka** [errorcalc/FreeEsVCLComponents#9]
Please see the attached registration error.  Help!
![REGISTRATION ERROR](https://user-images.githubusercontent.com/95257907/143960782-460e6d28-d496-4071-bb2e-326197fb79c0.jpg)

**Comment by jaddwooka** [comment]
Ok.  I figured this out.  This only happens when you start the IDE in "DPI Unaware" mode.  I'm not sure why but when I started the IDE normally, I could install just fine.

**Comment by errorcalc** [comment]
Thanks, with these details I try reproduce this error

**Comment by errorcalc** [comment]
I checked the latest components release in the latest IDE release in all modes and found no any errors.
